  export const allapi = [
    {
        "id": 1,
        "title":"HP Laptop 39.6 cm 15s-fq5326TU",
        "description":"12th Generation Intel® Core™ i3 processor, Windows 11 Home Single Language, 39.6 cm (15.6) diagonal FHD display with Intel® UHD Graphics, 8 GB DDR4 RAM, 512 GB SSD Hard drive, True Vision 720p HD camera",
        "brand":"hp",
        "category":"laptop",
        "image":"https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000189_11.png",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 9800",
        "discountpercent":"12",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000130_11.png",
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000159_11.png",
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000159_11.png",
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000130_11.png"            
                      ],
        "qty":20
    },
    {
        "id": 2,
        "title":"HP Laptop 39.6 cm 15s-eq2304AU",
        "description":"AMD Ryzen™ 5 processor Windows 11 Home Single Language 39.6 cm (15.6) diagonal FHD display with AMD Radeon™ Graphics 8 GB DDR4 RAM 512 GB SSD Hard drive Backlit keyboard with numeric keypad, True Vision 720p HD camera",
        "brand":"hp",
        "category":"laptop",
        "image":"https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000189_11.png",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 106000",
        "discountpercent":"12",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000130_11.png",
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000159_11.png",
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000159_11.png",
            "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/c/0/c08000130_11.png"            
                      ],
        "qty":20
    },
    {
        "id": 3,
        "title":"HP Envy Laptop 17t-cw000, 17.3",
        "description":"Windows 11 HomeIntel® Core™ i7-13700H (up to 5.0 GHz, 24 MB L3 cache, 14 cores, 20 threads) + Intel® Iris® Xe Graphics16 GB DDR4-3200 SDRAM (2 x 8 GB)512 GB PCIe® NVMe™ M.2 SSD",
        "brand":"hp",
        "category":"laptop",
        "image":"https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08904844.png?impolicy=Png_Res",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 106,000",
        "discountpercent":"12",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08904905.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08523887.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08523827.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08904875.png"            
                      ],
        "qty":20
    },
    {
        "id": 4,
        "title":"HP ProBook 450 15.6 inch G10 Notebook PC Wolf Pro Security Edition",
        "description":"Windows 11 Pro Intel® Core™ i7 1355U 5.0 GHz 32 GB DDR4-3200 MHz RAM (2 x 16 GB) 512 GB PCIe® NVMe™ SSD Intel® UHD Graphics",
        "brand":"hp",
        "category":"laptop",
        "image":"https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08473512.png?impolicy=Png_Res",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 760,000",
        "discountpercent":"12",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08473464.png?impolicy=Png_Res",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08473572.png?impolicy=Png_Res",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08475045.png?impolicy=Png_Res",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08471957.png?impolicy=Png_Res"            
                      ],
        "qty":20
    },
    {
        "id": 5,
        "title":"HP ZBook Firefly 16 inch G10 Mobile Workstation PC Wolf Pro Security Edition",
        "description":"Windows 11 ProIntel® Core™ i7-1370P (up to 5.2 GHz with Intel® Turbo Boost Technology, 24 MB L3 cache, 14 cores, 20 threads)64 GB DDR5-5200 MHz RAM (2 x 32 GB) WUXGA displayIntel® Iris® Xᵉ Graphics",
        "brand":"hp",
        "category":"laptop",
        "image":"https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08572748.png?impolicy=Png_Res",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 1,000,000",
        "discountpercent":"12",
        "warranty":"3 year standard warranty",
        "thumbnail":  [
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08572693.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08572839.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08572675.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08572821.png"            
                      ],
        "qty":20
    },
    {
        "id": 6,
        "title":"HP Spectre x360 2-in-1 Laptop 14t-eu000, 14",
        "description":"Windows 11 HomeIntel® Core™ Ultra 5 125H (up to 4.5 GHz, 18 MB L3 cache, 14 cores, 18 threads) + Intel® Arc™ Graphics + 16 GB(Onboard)512 GB PCIe® NVMe™ TLC M.2 SSD (4x4 SSD)",
        "brand":"hp",
        "category":"laptop",
        "image":"https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08873718.png",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 300,000",
        "discountpercent":"12",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08960935.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08745457.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08961295.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08961265.png"            
                      ],
        "qty":20
    },
    {
        "id": 7,
        "title":"HP EliteBook 1040 14 inch G9 Notebook PC Wolf Pro Security Edition",
        "description":"Windows 11 ProIntel® Core™ i7-1255U (up to 4.7 GHz with Intel® Turbo Boost Technology, 12 MB L3 cache, 10 cores, 12 threads)32 GB memory; 1 TB SSD storage14 diagonal WUXGA displayIntel® Iris® Xᵉ Graphics",
        "brand":"hp",
        "category":"laptop",
        "image":"https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08177526.png",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 929,000",
        "discountpercent":"12",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08177555.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08177440.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08177497.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08177408.png"            
                      ],
        "qty":20
    },
    {
        "id": 8,
        "title":"HP ZBook Power 15.6 inch G10 Mobile Workstation PC Wolf Pro Security Edition",
        "description":"Windows 11 ProIntel® Core™ i7-13700H (up to 5.0 GHz with Intel® Turbo Boost Technology, 24 MB L3 cache, 14 cores, 20 threads)32 GB memory; 1 TB SSD storage15.6 diagonal FHD displayNVIDIA RTX™ A1000 Laptop GPU (6 GB GDDR6 dedicated)",
        "brand":"hp",
        "category":"laptop",
        "image":"https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08677733.png",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 1,144,000",
        "discountpercent":"12",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08677673.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08575202.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08575240.png",
            "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08677643.png"            
                      ],
        "qty":20
    },
    {
        "id": 9,
        "title":"Dell G15 5530 Core i7 13th Generation 8GB RAM 1TB SSD 6GB RTX 4050 Windows 11",
        "description":"The latest Dell G15 5530 Core i7 13th Generation 8GB RAM 1TB SSD 6GB RTX 4050 Windows 11 price in Pakistan is 313,999 - PKR which was recently updated on April 2024 Basic specification is Core i7 13th Generation i7 13650HX, RAM: 8GB , Screen: 15.6 Inch, OS: Windows 11, Storage: 1TB SSD, SSD, Speed: up to 4.90 GHz ,.",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+G15+5530+Core+i7+13th+Generation+8GB+RAM+1TB+SSD+6GB+RTX+4050+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_24644.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 344,000",
        "discountpercent":"8",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://www.czone.com.pk/images/content/9930a83d-c8c8-4b4a-ad8b-c3557104bdd9.png",
            "https://www.czone.com.pk/images/thumbnails-large/20-czone.com.pk-1540-15317-051023093512.jpg",
            "https://www.czone.com.pk/images/thumbnails-large/21-czone.com.pk-1540-15317-051023093513.jpg",
            "https://www.czone.com.pk/images/thumbnails-large/22-czone.com.pk-1540-15317-051023093514.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 10,
        "title":"Dell G15 5530 Core i7 13th Generation 16GB RAM 512GB SSD 8GB RTX 4060 Windows 11",
        "description":"The latest Dell G15 5530 Core i7 13th Generation 16GB RAM 512GB SSD 8GB RTX 4060 Windows 11 price in Pakistan is 382,999 - PKR which was recently updated on April 2024 Basic specification is Core i7 13th Generation i7 13650HX, RAM: 16GB , Screen: 15.6 Inch, OS: Windows 11, Storage: 512GB, SSD, Speed: up to 4.90 GHz ",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+G15+5530+Core+i7+13th+Generation+16GB+RAM+512GB+SSD+8GB+RTX+4060+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_24408.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 382,999",
        "discountpercent":"8",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://www.czone.com.pk/images/thumbnails-large/copy-7-czone.com.pk-1540-15388-261023070331-1540-15669-260124095856.jpg",
            "https://www.czone.com.pk/images/thumbnails-large/copy-8-czone.com.pk-1540-15388-261023070332-1540-15669-260124095857.jpg",
            "https://www.czone.com.pk/images/thumbnails-large/copy-11-czone.com.pk-1540-15388-261023070607-1540-15669-260124095857.jpg",
            "https://www.czone.com.pk/images/thumbnails-large/20-czone.com.pk-1540-15669-260124095857.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 11,
        "title":"Dell Alienware M18 Core i9 13th Generation 64GB RAM 4TB SSD 16GB RTX 4090 Windows 11",
        "description":"The latest Dell Alienware M18 Core i9 13th Generation 64GB RAM 4TB SSD 16GB RTX 4090 Windows 11 price in Pakistan is 1,379,999 - PKR which was recently updated on April 2024 Basic specification is Core i9 13th Generation i9-13980HK, RAM: 64GB , Screen: 18 Inches, OS: Windows 11, Storage: 4TB SSD, SSD, Speed: up to 5.4 GHz ",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+Alienware+M18+Core+i9+13th+Generation+64GB+RAM+4TB+SSD+16GB+RTX+4090+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_25015.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 1,380,999",
        "discountpercent":"2",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://m.media-amazon.com/images/I/913g3IULc6L._AC_SX679_.jpg",
            "https://m.media-amazon.com/images/I/616lM1oW1BL._AC_SX679_.jpg",
            "https://m.media-amazon.com/images/I/61aUhey3IkL._AC_SX679_.jpg",
            "https://m.media-amazon.com/images/I/61bhovcPn6L._AC_SX679_.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 12,
        "title":"Dell Alienware X16 Core i9 13th Generation 32GB RAM 1TB SSD 12GB RTX 4080 Windows 11",
        "description":"The latest Dell Alienware X16 Core i9 13th Generation 32GB RAM 1TB SSD 12GB RTX 4080 Windows 11 price in Pakistan is 859,999 - PKR which was recently updated on April 2024 Basic specification is Core i9 13th Generation i9-13900HK, RAM: 32GB , Screen: 16 Inches, OS: Windows 11, Storage: 1TB SSD, SSD, Speed: up to 5.4 GHz ",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+Alienware+X16+Core+i9+13th+Generation+32GB+RAM+1TB+SSD+12GB+RTX+4080+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_25014.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 860,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://m.media-amazon.com/images/I/71WJ2jTqZgL._AC_SX679_.jpg",
            "https://m.media-amazon.com/images/I/710vE1sML4L._AC_SX679_.jpg",
            "https://m.media-amazon.com/images/I/713wPLDA6nL._AC_SX679_.jpg",
            "https://m.media-amazon.com/images/I/8140BKGtafL._AC_SX679_.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 13,
        "title":"Dell Alienware M18 Core i9 14th Generation 32GB RAM 2TB SSD 12GB RTX 4080 Windows 11",
        "description":"The latest Dell Alienware M18 Core i9 14th Generation 32GB RAM 2TB SSD 12GB RTX 4080 Windows 11 price in Pakistan is 1,219,999 - PKR which was recently updated on April 2024 Basic specification is Core i9 14th Generation i9-14900HX, RAM: 32GB , Screen: 18 Inches, OS: Windows 11, Storage: 2TB SSD, SSD, Speed: up to 5.8 GHz ",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+Alienware+M18+Core+i9+14th+Generation+32GB+RAM+2TB+SSD+12GB+RTX+4080+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_24988.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 1,219,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://www.dotcom.com.pk/wp-content/uploads/2023/07/Untitled-1.png.webp",
            "https://www.dotcom.com.pk/wp-content/uploads/2023/07/Untitled-2.png.webp",
            "https://www.dotcom.com.pk/wp-content/uploads/2023/07/Untitled-3.png.webp",
            "https://www.dotcom.com.pk/wp-content/uploads/2023/07/Untitled-1.png.webp"            
                      ],
        "qty":20
    },
    {
        "id": 14,
        "title":"Dell G16 7630 Core i9 13th Generation 16GB RAM 1TB SSD 8GB RTX 4070 Windows 11",
        "description":"The latest Dell G16 7630 Core i9 13th Generation 16GB RAM 1TB SSD 8GB RTX 4070 Windows 11 price in Pakistan is 484,999 - PKR which was recently updated on April 2024 Basic specification is Core i9 13th Generation i9-13900HX, RAM: 16GB , Screen: 16 Inches, OS: Windows 11, Storage: 1TB SSD, SSD, Speed: up to 5.40 GHz ",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+G16+7630+Core+i9+13th+Generation+16GB+RAM+1TB+SSD+8GB+RTX+4070+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_24961.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 484,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/d/e/dell_g16_7630_gaming_laptop.44_am.jpg.webp",
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/d/e/dell_g16_7630_gaming_laptop.45_am.jpg.webp",
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/d/e/dell_g16_7630_gaming_laptop.20_am.jpg.webp",
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/d/e/dell_g16_7630_gaming_laptop.33_am.jpg.webp"            
                      ],
        "qty":20
    },
    {
        "id": 15,
        "title":"Dell Alienware M16 Core i9 13th Generation 16GB RAM 1TB SSD 12GB RTX 4080 Windows 11",
        "description":"The latest Dell Alienware M16 Core i9 13th Generation 16GB RAM 1TB SSD 12GB RTX 4080 Windows 11 price in Pakistan is 784,999 - PKR which was recently updated on April 2024 Basic specification is Core i9 13th Generation i9-13900HX, RAM: 16GB , Screen: 16 Inches, OS: Windows 11, Storage: 1TB SSD, SSD, Speed: up to 5.4 GHz ",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+Alienware+M16+Core+i9+13th+Generation+16GB+RAM+1TB+SSD+12GB+RTX+4080+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_24781.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 784,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/a/c/acer_nitro_v_15_.02_pm.jpg.webp",
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/a/c/acer_nitro_v_15_.07_pm.jpg.webp",
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/a/c/acer_nitro_v_15_.09_pm.jpg.webp",
            "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/a/c/acer_nitro_v_15_.12_pm.jpg.webp"            
                      ],
        "qty":20
    },
    {
        "id": 16,
        "title":"Dell XPS 15 9530 Core i9 13th Generation 64GB RAM 1TB SSD 8GB RTX 4060 Touch Windows 11",
        "description":"The latest Dell XPS 15 9530 Core i9 13th Generation 64GB RAM 1TB SSD 8GB RTX 4060 Touch Windows 11 price in Pakistan is 789,999 - PKR which was recently updated on April 2024 Basic specification is Core i9 13th Generation i9-13900H, RAM: 64GB , Screen: 15.6 inch , OS: Windows 11, Storage: 1 TB, SSD, Speed: up to 5.4 GHz ",
        "brand":"dell",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Dell+XPS+15+9530+Core+i9+13th+Generation+64GB+RAM+1TB+SSD+8GB+RTX+4060+Touch+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_24731.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 789,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9530/media-gallery/touch-black/notebook-xps-15-9530-t-black-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=654&qlt=100,1&resMode=sharp2&size=654,402&chrss=full",
            "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9530/media-gallery/touch-black/notebook-xps-15-9530-t-black-gallery-4.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=677&qlt=100,1&resMode=sharp2&size=677,402&chrss=full",
            "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9530/media-gallery/touch-black/notebook-xps-15-9530-t-black-gallery-5.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=677&qlt=100,1&resMode=sharp2&size=677,402&chrss=full",
            "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9530/media-gallery/touch-black/notebook-xps-15-9530-t-black-gallery-3.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=518&qlt=100,1&resMode=sharp2&size=518,402&chrss=full"            
                      ],
        "qty":20
    },
    {
        "id": 17,
        "title":"Apple MacBook Pro MUW63 16 M3 Max Chip 16 Core CPU 40 Core GPU 48GB RAM 1TB SSD",
        "description":"Rendering times up to 2.5 times faster than a 16-inch MacBook Pro M1 in M3 Chip Performance with up to 80% quicker CPU multithreading than the 16-inch MacBook Pro with M1 Max Super performance is powered by next-generation CPU cores, which also deliver amazing power efficiency. At up to 22 hours, the MacBook Pro boasts the greatest battery life of any Mac device. The secret of Apple silicon's brilliance is its efficiency. Moreover, all models maintain the same speed whether plugged in or not ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Pro+MUW63+16+M3+Max+Chip+16+Core+CPU+40+Core+GPU+48GB+RAM+1TB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_24680.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 1,169,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://static3.webx.pk/files/4012/Images/1-4012-1918225-211123013920719.jpg",
            "https://static3.webx.pk/files/4012/Images/4-4012-1918225-211123013930993.jpg",
            "https://static3.webx.pk/files/4012/Images/2-4012-1918225-211123013930951.jpg",
            "https://static3.webx.pk/files/4012/Images/3-4012-1918225-211123013931111.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 18,
        "title":"Apple MacBook Pro 14 M3 Max Chip 14 Core CPU 30 Core GPU 36GB RAM 1TB SSD",
        "description":"Rendering times up to 2.5 times faster than a 16-inch MacBook Pro M1 in M3 Chip Performance with up to 80% quicker CPU multithreading than the 16-inch MacBook Pro with M1 Max Super performance is powered by next-generation CPU cores, which also deliver amazing power efficiency. At up to 22 hours, the MacBook Pro boasts the greatest battery life of any Mac device. The secret of Apple silicon's brilliance is its efficiency. Moreover, all models maintain the same speed whether plugged in or not. ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Pro+14+M3+Max+Chip+14+Core+CPU+30+Core+GPU+36GB+RAM+1TB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_24675.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 1,006,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://cityshop.com.pk/wp-content/uploads/2023/11/macbook-pro-14inch-16inch-m3-max-space-black.jpg",
            "https://cityshop.com.pk/wp-content/uploads/2023/11/macbook-pro-m3-space-black-2023.jpg",
            "https://cityshop.com.pk/wp-content/uploads/2023/11/macbook-pro-m3-space-black-back-side-pic-cityshop.jpg",
            "https://cityshop.com.pk/wp-content/uploads/2023/11/macbook-pro-m3-space-black-side-pic-cityshop.com_.pk_.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 19,
        "title":"Apple MacBook Air M3 Chip 8 Core CPU 10 Core GPU 16GB Ram 512GB SSD",
        "description":"The latest Apple MacBook Air M3 Chip 8 Core CPU 10 Core GPU 16GB Ram 512GB SSD price in Pakistan is 504,999 - PKR which was recently updated on April 2024 Basic specification is Apple M3 Chip, RAM: 16GB , Screen: 13.6 Inch, OS: macOS, Storage: 512GB SSD, SSD, Speed: 8 Core CPU with 4 performance Cores and 4 efficiency Cores,. ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Air+M3+Chip+8+Core+CPU+10+Core+GPU+16GB+Ram+512GB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_25058.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 504,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://cityshop.com.pk/wp-content/uploads/2024/03/apple-macbook-air-m3-13.6-inch-space-gray.jpg",
            "https://cityshop.com.pk/wp-content/uploads/2024/03/apple-macbook-air-m3-13.6-inch-top-side-apple-logo-pic.jpg",
            "https://cityshop.com.pk/wp-content/uploads/2024/03/apple-macbook-air-m3-13.6-inch-keyboard-touchid-pic.jpg",
            "https://cityshop.com.pk/wp-content/uploads/2024/03/apple-macbook-air-m3-13.6-inch-side-ports-pic-860x645.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 20,
        "title":"Apple MacBook Air 15 MQKX3 M2 Chip 8GB Ram 512GB SSD",
        "description":"8 Core CPU with 4 Performance Cores and 4 Efficiency cores 10 Core GPU 500 nits brightness Battery Up to 18 hours USB-C to MagSafe 3 Cable 3.5 mm Headphone Jack Touch ID Four Speaker Sound System. The new M2 chip makes the 15.3 inch MacBook more capable than ever. The same compact design supports up to 20 hours of battery life1 and an active cooling system to sustain enhanced performance. Featuring a brilliant Retina display, a FaceTime HD camera, and studio quality mics, it's our most portable pro laptop. ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Air+15+MQKX3+M2+Chip+8GB+Ram+512GB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_24992.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 401,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://zahcomputers.pk/wp-content/uploads/2023/07/Apple-MacBook-Air-Price-in-Pakistan.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/07/Apple-MacBook-Air-Price-in-Pakistan-01.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/07/Apple-MacBook-Air-Price-in-Pakistan-04.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/07/Apple-MacBook-Air-Price-in-Pakistan-06.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 21,
        "title":"Apple MacBook Air 15 MQKU3 M2 Chip 8GB Ram 256GB SSD",
        "description":"8 Core CPU with 4 Performance Cores and 4 Efficiency cores 10 Core GPU 500 nits brightness Battery Up to 18 hours USB-C to MagSafe 3 Cable 3.5 mm Headphone Jack Touch ID Four Speaker Sound System. The new M2 chip makes the 15.3 inch MacBook more capable than ever. The same compact design supports up to 20 hours of battery life1 and an active cooling system to sustain enhanced performance. Featuring a brilliant Retina display, a FaceTime HD camera, and studio quality mics, it's our most portable pro laptop. ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Air+15+MQKU3+M2+Chip+8GB+Ram+256GB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_24991.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 334,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Air-MQKU3.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Air-MQKU3-01.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Air-MQKU3-04-150x150.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Air-MQKU3-07.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 22,
        "title":"Apple MacBook Air M3 Chip 8 Core CPU 8 Core GPU 8GB Ram 256GB SSD",
        "description":"The latest Apple MacBook Air M3 Chip 8 Core CPU 8 Core GPU 8GB Ram 256GB SSD price in Pakistan is 349,999 - PKR which was recently updated on April 2024 Basic specification is Apple M3 Chip, RAM: 8GB , Screen: 13.6 Inch, OS: macOS, Storage: 256GB , SSD, Speed: 8 Core CPU with 4 performance Cores and 4 efficiency Cores ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Air+M3+Chip+8+Core+CPU+8+Core+GPU+8GB+Ram+256GB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_24978.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 349,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://zahcomputers.pk/wp-content/uploads/2022/09/Apple-13.6-MacBook-Air-MLXW3-Price-in-Pakistan.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2022/09/Apple-13.6-MacBook-Air-MLXW3-Price-in-Pakistan-01.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2022/09/Apple-13.6-MacBook-Air-MLXW3-Price-in-Pakistan-02.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2022/09/Apple-13.6-MacBook-Air-MLXW3-Price-in-Pakistan-04.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 23,
        "title":"Apple MacBook Pro 16 MRW23 M3 Pro Chip 12 Core CPU 18 Core GPU 36GB RAM 512GB SSD",
        "description":"Rendering times up to 2.5 times faster than a 16-inch MacBook Pro M1 in M3 Chip Performance with up to 80% quicker CPU multithreading than the 16-inch MacBook Pro with M1 Max Super performance is powered by next-generation CPU cores, which also deliver amazing power efficiency. At up to 22 hours, the MacBook Pro boasts the greatest battery life of any Mac device. The secret of Apple silicon's brilliance is its efficiency. Moreover, all models maintain the same speed whether plugged in or not. ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Pro+16+MRW23+M3+Pro+Chip+12+Core+CPU+18+Core+GPU+36GB+RAM+512GB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_24702.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 789,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Pro-16-M3-Space-Black.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Pro-16-M3-Space-Black-01.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Pro-16-M3-Space-Black-04.jpg",
            "https://zahcomputers.pk/wp-content/uploads/2023/11/Apple-MacBook-Pro-14-M3.jpg"            
                      ],
        "qty":20
    },
    {
        "id": 24,
        "title":"Apple MacBook Pro 16 MRW33 M3 Max Chip 14 Core CPU 30 Core GPU 36GB RAM 1TB SSD",
        "description":"Rendering times up to 2.5 times faster than a 16-inch MacBook Pro M1 in M3 Chip Performance with up to 80% quicker CPU multithreading than the 16-inch MacBook Pro with M1 Max Super performance is powered by next-generation CPU cores, which also deliver amazing power efficiency. At up to 22 hours, the MacBook Pro boasts the greatest battery life of any Mac device. The secret of Apple silicon's brilliance is its efficiency. Moreover, all models maintain the same speed whether plugged in or not. ",
        "brand":"apple",
        "category":"laptop",
        "image":"https://www.mega.pk/items_images/Apple+MacBook+Pro+16+MRW33+M3+Max+Chip+14+Core+CPU+30+Core+GPU+36GB+RAM+1TB+SSD+Price+in+Pakistan%2C+Specifications%2C+Features_-_24679.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 1,019,999",
        "discountpercent":"4",
        "warranty":"1 year (1/1/0) limited warranty includes 1 year of parts and labor. No on-site repair. Terms and conditions vary by country. Certain restrictions and exclusions apply.",
        "thumbnail":  [
            "https://appleshop.com.pk/wp-content/uploads/2023/10/mbp16-spaceblack-gallery6-768x590.jpeg",
            "https://appleshop.com.pk/wp-content/uploads/2023/10/mbp14-m3-max-pro-spaceblack-gallery1.jpeg",
            "https://appleshop.com.pk/wp-content/uploads/2023/10/mbp16-spaceblack-gallery2.jpeg",
            "https://appleshop.com.pk/wp-content/uploads/2023/10/mbp16-spaceblack-gallery5.jpeg"            
                      ],
        "qty":20
    },
    {
        "id": 25,
        "title":"AirPods Pro (2nd generation) with MagSafe Charging Case (USB‑C)",
        "description":"Engrave a mix of emoji, names, initials, and numbers to make AirPods unmistakably yours. Only at Apple To purchase with monthly pricing, add this item to your bag and choose to check out with Apple Card Monthly Installments. ",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MTJV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1694014871985",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 70,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MTJV3_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1694014867061",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MTJV3_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1694014868810",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MTJV3_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1694014871550",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MTJV3_AV4?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1694014874426"            
                      ],
        "qty":20
    },
    {
        "id": 26,
        "title":"AirPods (3rd generation) with MagSafe Charging Case",
        "description":"Engrave a mix of emoji, names, initials, and numbers to make AirPods unmistakably yours. Only at Apple To purchase with monthly pricing, add this item to your bag and choose to check out with Apple Card Monthly Installments ",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV7N2?wid=890&hei=890&fmt=jpeg&qlt=95&.v=1551489688005",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 50,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MME73_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1632861333000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MME73_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1632861336000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MME73_AV4?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1632861336000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MME73_AV5?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1633733312000"            
                      ],
        "qty":20
    },
    {
        "id": 27,
        "title":"AirPods Max",
        "description":"Add Engraving Engrave a mix of emoji, names, initials, and numbers to make AirPods Max unmistakably yours. Only at Apple",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-skyblue-202011?wid=940&hei=1112&fmt=png-alpha&.v=1604022365000",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 150,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-spacegray-202011?wid=940&hei=1112&fmt=png-alpha&.v=1604709508000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-green-202011?wid=940&hei=1112&fmt=png-alpha&.v=1604022364000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-silver-202011?wid=940&hei=1112&fmt=png-alpha&.v=1604021221000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-pink-202011?wid=940&hei=1112&fmt=png-alpha&.v=1604022365000"            
                      ],
        "qty":20
    },
    {
        "id": 28,
        "title":"Beats Studio Buds + True Wireless Noise Cancelling Earbuds — Transparent",
        "description":"Keep all your selections by saving this device to Your Saves, then come back anytime and pick up right where you left off",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQLK3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1682361480894",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 47,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQLK3_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1682361479820",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQLK3_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1682361478796",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQLK3_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1682361478080",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQLK3_AV5?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1682361479245"            
                      ],
        "qty":20
    },
    {
        "id": 29,
        "title":"Beats Studio Buds True Wireless Noise Cancelling Earphones – Beats Red",
        "description":"Beats was born to deliver music as the artist intended. Beats Studio Buds are engineered to deliver powerful, balanced sound in a compact design, through an entirely customized acoustic platform. A proprietary, dual-element diaphragm driver resides within a two-chamber housing, resulting in clear sound with outstanding stereo separation",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJ503?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1621538312000",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 41,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJ503_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1621538267000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJ503_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1621538257000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJ503_AV3_v4?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1621538274000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MJ503_AV4?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1682095928197"            
                      ],
        "qty":20
    },
    {
        "id": 30,
        "title":"Beats Solo3 Wireless Headphones - Gold",
        "description":"With up to 40 hours of battery life, Beats Solo3 Wireless is your perfect everyday headphone. With Fast Fuel, a 5-minute charge gives you 3 hours of playback. Enjoy award-winning Beats sound with Class 1 Bluetooth wireless listening freedom. The on-ear, cushioned ear cups are adjustable so you can customize your fit for all-day comfort.",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MT283?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1695245036798",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 55,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MT283_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1695245032992",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MT283_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1695245033128",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MT283_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1695245034086",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MT283_AV4?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1695245033842"            
                      ],
        "qty":20
    },
    {
        "id": 31,
        "title":"Powerbeats Pro - True Wireless Earbuds - Navy",
        "description":"Powerbeats Pro, powered by the Apple H1 headphone chip, will revolutionize the way you work out. Built for elite athletes, these true wireless earbuds have no wires to hold you back. The adjustable, secure-fit earhooks are customizable with multiple ear-tip options for extended comfort and are made to stay in place, no matter how hard you go",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV702?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1602803373000",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 70,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV702_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1602803377000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV702_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1602803366000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV702_AV4?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1602803294000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV702_AV5?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1602803343000"            
                      ],
        "qty":20
    },
    {
        "id": 32,
        "title":"Incase AirPods Case with Woolenex - Asphalt",
        "description":"The Incase AirPods Case with Woolenex safeguards the Wireless Charging Case that protects and powers your AirPods. This lightweight, form-fitting case is crafted with refined, durable Woolenex—a lightweight fabric blend with excellent abrasion and weather resistance—that adds an element of sophisticated style while protecting the glossy Wireless Charging Case from scuffs and scratches",
        "brand":"apple",
        "category":"airpords",
        "image":"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HNEY2?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1626150118000",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 8,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HNEY2_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1626150089000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HNEY2_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1626150100000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HNEY2_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1626150121000",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HNEY2_AV4?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1626150114000"            
                      ],
        "qty":20
    },
    {
        "id": 33,
        "title":"Elite 1000 Sound Bar With Woofer",
        "description":"Wireless Subwoofer: 6.5 Soundbar Drivers: 2.25 x 4 RMS 160 Watt Remote Control/LED display",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/ELITEBAR1000-6.png?v=1709884113",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 37,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/ELITEBAR1000-1.png?v=1709884113",
            "https://audionic.co/cdn/shop/files/ELITEBAR1000-2.png?v=1709884113",
            "https://audionic.co/cdn/shop/files/ELITEBAR1000-3.png?v=1709884113",
            "https://audionic.co/cdn/shop/files/ELITEBAR1000-4.png?v=1709884113"            
                      ],
        "qty":20
    },
    {
        "id": 34,
        "title":"Optima Sound Bar",
        "description":"4 Hours play time 10W dual Drivers Portable Bluetooth Connectivity",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/Png-min.png?v=1701169509",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 10,999",
        "discountpercent":"48",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/3-min.png?v=1701169509",
            "https://audionic.co/cdn/shop/files/2-min.png?v=1701169509",
            "https://audionic.co/cdn/shop/files/4-min.png?v=1701169510",
            "https://audionic.co/cdn/shop/files/1-min.png?v=1701169510"            
                      ],
        "qty":20
    },
    {
        "id": 35,
        "title":"AD-7000 PLUS 2.1 MULTIMEDIA SPEAKER (AC/DC SUPPORTED)",
        "description":"Experience music with the awesome AD-7000 plus 2.1 multimedia speaker of Pakistan. You can play the audio files, which you want to play directly from flash drive and SD or MMC card. It comes with digital display because of its modern technology. It has wireless small remote control, which performs the multiple functions of multimedia speaker; but the most important function of the wireless remote is to control the audio by adjusting the sound volume of the sub-woofer multimedia speaker according to your mood or occasion.",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-ad-7000-plus-2-1-multimedia-speaker-ac-dc-supported-33845783101596.png?v=1693983098",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 40,999",
        "discountpercent":"6",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-ad-7000-plus-2-1-multimedia-speaker-ac-dc-supported-33993105408156.png?v=1693983105",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-ad-7000-plus-2-1-multimedia-speaker-ac-dc-supported-33993105473692.png?v=1693983107",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-ad-7000-plus-2-1-multimedia-speaker-ac-dc-supported-33845783101596.png?v=1693983098",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-ad-7000-plus-2-1-multimedia-speaker-ac-dc-supported-33993105408156.png?v=1693983105"            
                      ],
        "qty":20
    },
    {
        "id": 36,
        "title":"Prism 800 Soundbar With Woofer",
        "description":"You can connect the system to your TV via an AUX cable or Bluetooth HDMI or Optical Cable. Plug one end into the Audio Output of your TV and the other end into the Audio Input of the Prism 800 Soundbar system. If your TV supports Bluetooth, you can also pair the speaker system wirelessly.",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/PRISM800-11.png?v=1709883989",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 34,999",
        "discountpercent":"4",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/PRISM800-6.png?v=1709883989",
            "https://audionic.co/cdn/shop/files/PRISM800-1.png?v=1709883989",
            "https://audionic.co/cdn/shop/files/PRISM800-5.png?v=1709883989",
            "https://audionic.co/cdn/shop/files/PRISM800-4.png?v=1709883989"            
                      ],
        "qty":20
    },
    {
        "id": 37,
        "title":"Mega 40 (2.1 Channel HiFi Speaker)",
        "description":"You may place an order by adding it to your cart from the website, and then entering your address and other details, select your payment option and your order will be placed.",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mega-40-2-1-channel-hifi-speaker-33845860925596.png?v=1693983586",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 26,000",
        "discountpercent":"48",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mega-40-2-1-channel-hifi-speaker-33993131262108.png?v=1693983597",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mega-40-2-1-channel-hifi-speaker-33993131098268.png?v=1693983602",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mega-40-2-1-channel-hifi-speaker-33993131065500.png?v=1693983594",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mega-40-2-1-channel-hifi-speaker-33845860925596.png?v=1693983586"            
                      ],
        "qty":20
    },
    {
        "id": 38,
        "title":"MREBORN RB-110 (2.1 CHANNEL MULTIMEDIA SPEAKER)",
        "description":"Make your lounge a cinema with REBORN RB-110 sound speaker home theater system to experience a real theater, now you can fully enjoy your favorite television shows, movies with your friends, family, relatives and of course with your loved ones in a definitely good and cinematic environment at home with the best, clear and high quality audio of your choice without any disturbance with the best budget surround home sound system for television in Pakistan.",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-reborn-rb-110-2-1-channel-multimedia-speaker-30640629022876-PhotoRoom.png-PhotoRoom.png?v=1700140997",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 39,000",
        "discountpercent":"20",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-reborn-rb-110-2-1-channel-multimedia-speaker-30640629088412-PhotoRoom.png-PhotoRoom.png?v=1700140997",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-reborn-rb-110-2-1-channel-multimedia-speaker-30640629285020-PhotoRoom.png-PhotoRoom.png?v=1700140997",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-reborn-rb-110-2-1-channel-multimedia-speaker-30640629219484-PhotoRoom.png-PhotoRoom.png?v=1700140997",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-reborn-rb-110-2-1-channel-multimedia-speaker-30640629252252-PhotoRoom.png-PhotoRoom.png?v=1700140997"            
                      ],
        "qty":20
    },
    {
        "id": 39,
        "title":"Prism 500 Soundbar With Woofer",
        "description":"You can connect the system to your TV via an AUX cable or Bluetooth. Plug one end into the Audio Output of your TV and the other end into the Audio Input of the Prism 500 Soundbar system. If your TV supports Bluetooth, you can also pair the speaker system wirelessly.",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/Prism500finalpng.png?v=1709884048",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 50,000",
        "discountpercent":"45",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/1png_14943cc1-a3b2-41a0-93cf-5b819091181f.png?v=1709884048",
            "https://audionic.co/cdn/shop/files/2_fb635e7b-2e84-4a84-85f8-8b35ed38470c.png?v=1709884048",
            "https://audionic.co/cdn/shop/files/3_c6419122-4ed6-44e7-a800-06d5658de1dc.png?v=1709884048",
            "https://audionic.co/cdn/shop/files/Prism500finalpng.png?v=1709884048"            
                      ],
        "qty":20
    },
    {
        "id": 40,
        "title":"MH-801 Bluetooth Speaker With Mic",
        "description":"You can control speaker through remote that comes with some models if your model does not have a remote then use the button and volume dial available on the speaker itself.",
        "brand":"audionic",
        "category":"speakers",
        "image":"https://audionic.co/cdn/shop/files/MH-801_1.png?v=1709116389",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 20,000",
        "discountpercent":"45",
        "warranty":"2 month",
        "thumbnail":  [
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mh-801-bluetooth-speaker-with-mic-34658192654492.png?v=1709116389",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mh-801-bluetooth-speaker-with-mic-34658192785564.png?v=1709116389",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mh-801-bluetooth-speaker-with-mic-34658192687260.png?v=1709116389",
            "https://audionic.co/cdn/shop/files/audionic-the-sound-master-default-title-mh-801-bluetooth-speaker-with-mic-34658192621724.png?v=1709116389"            
                      ],
        "qty":20
    },
    {
        "id": 41,
        "title":"Apple iPhone 15 Plus",
        "description":"Apple's iPhone 15 Pro Max dazzles with cutting-edge features. Its 6.7-inch Super Retina XDR display delivers stunning visuals, while the A17 Bionic chip ensures lightning-fast performance. The enhanced camera system captures pro-quality photos and videos, and the 5G connectivity keeps you connected at blazing speeds. With sleek design and advanced technology, the iPhone 15 Pro Max sets a new standard in smartphone excellence.",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/apple-iphone-15-plus-pakistan-priceoye-tauhi-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 554,000",
        "discountpercent":"14",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/apple-iphone-15-plus-pakistan-priceoye-oeyfg-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-15-plus-pakistan-priceoye-s6o6n-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-15-plus-pakistan-priceoye-ukcvm-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-15-plus-pakistan-priceoye-ugmqg-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 42,
        "title":"Apple iPhone 14 Pro",
        "description":"Apple's iPhone 15 Pro Max dazzles with cutting-edge features. Its 6.7-inch Super Retina XDR display delivers stunning visuals, while the A17 Bionic chip ensures lightning-fast performance. The enhanced camera system captures pro-quality photos and videos, and the 5G connectivity keeps you connected at blazing speeds. With sleek design and advanced technology, the iPhone 15 Pro Max sets a new standard in smartphone excellence.",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/iphone-14-pro-pakistan-priceoye-sibh5-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 530,000",
        "discountpercent":"5",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/iphone-14-pro-pakistan-priceoye-uptsl-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-14-pro-pakistan-priceoye-fmnxi-500x500.webp",
            "https://images.priceoye.pk/iphone-14-pro-pakistan-priceoye-1ejzq-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-15-plus-pakistan-priceoye-ugmqg-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 43,
        "title":"Apple iPhone 11",
        "description":"Apple's iPhone 11 offers impressive features at an affordable price. Its 6.1-inch Liquid Retina display showcases vibrant colors, powered by the A13 Bionic chip for seamless performance. The dual-camera system captures stunning photos and 4K videos. With all-day battery life and iOS updates, the iPhone 11 delivers exceptional value for everyday users",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/apple-iphone-xi-pakistan-priceoye-xrcfl-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 148,000",
        "discountpercent":"2",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/apple-iphone-xi-pakistan-priceoye-2kaqt-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-xi-pakistan-priceoye-v9a8i-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-xi-pakistan-priceoye-rscx5-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-xi-pakistan-priceoye-kb5ul-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 44,
        "title":"Apple iPhone 13",
        "description":"Apple's iPhone 13 redefines excellence with its 6.1-inch Super Retina XDR display and A15 Bionic chip, delivering unmatched performance. The advanced dual-camera system captures striking photos and videos, while 5G connectivity ensures lightning-fast speeds. With longer battery life and iOS updates, the iPhone 13 sets a new benchmark for innovation and user experience.",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/apple-iphone-13-pakistan-priceoye-y1wwo-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 334,999",
        "discountpercent":"2",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/apple-iphone-13-pakistan-priceoye-198ir-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-13-pakistan-priceoye-2nziq-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-13-pakistan-priceoye-n6uie-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-13-pakistan-priceoye-un2vy-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 45,
        "title":"Apple iPhone 12 Pro Max",
        "description":"Apple's iPhone 12 Pro Max combines raw power with sleek design. Its 6.7-inch Super Retina XDR display and A14 Bionic chip offer unmatched performance. The triple-camera system captures professional-quality photos and Dolby Vision HDR videos. With 5G capabilities and MagSafe accessories, the iPhone 12 Pro Max delivers an immersive and seamless user experience.",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/apple-iphone-12-pro-max-pakistan-priceoye-aam6w-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 241,999",
        "discountpercent":"2",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/apple-iphone-12-pro-max-pakistan-priceoye-swc34-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-12-pro-max-pakistan-priceoye-o4ngc-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-12-pro-max-pakistan-priceoye-nwhxh-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-12-pro-max-pakistan-priceoye-aam6w-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 46,
        "title":"Apple iPhone XS Max",
        "description":"Apple's iPhone XS Max boasts a stunning 6.5-inch Super Retina OLED display and the powerful A12 Bionic chip for smooth multitasking. Its dual-camera system captures breathtaking photos and 4K videos. With Face ID security and wireless charging, the iPhone XS Max combines luxury with cutting-edge technology for a premium smartphone experience.",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/apple-iphone-xs-max-pakistan-priceoye-0edys-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 170,999",
        "discountpercent":"1",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/apple-iphone-xs-max-pakistan-priceoye-qo5qi-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-xs-max-pakistan-priceoye-573c7-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-xs-max-pakistan-priceoye-1ctur-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-xs-max-pakistan-priceoye-gysl1-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 47,
        "title":"Apple iPhone 11 Pro Max",
        "description":"Apple's iPhone 11 Pro Max excels with its 6.5-inch Super Retina XDR display and A13 Bionic chip, ensuring top-notch performance. Its triple-camera system captures stunning photos and 4K videos. With all-day battery life, Face ID, and iOS updates, the iPhone 11 Pro Max delivers a seamless and sophisticated mobile experience for discerning users.",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/apple-iphone-11-pro-max-pakistan-priceoye-x8a6v-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 226,999",
        "discountpercent":"3",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/apple-iphone-11-pro-max-pakistan-priceoye-x8a6v-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-11-pro-max-pakistan-priceoye-n7vp8-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-11-pro-max-pakistan-priceoye-9aply-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-11-pro-max-pakistan-priceoye-87w75-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 48,
        "title":"Apple iPhone 15 Pro max",
        "description":"Apple's iPhone 15 Pro Max is a marvel of innovation, featuring a 6.7-inch Super Retina XDR display and the powerful A17 Bionic chip for unparalleled performance. Its advanced camera system captures pro-level photos and videos, while 5G connectivity ensures lightning-fast speeds. With sleek design, enhanced security features, and seamless integration, the iPhone 15 Pro Max sets a new standard for premium smartphones.        ",
        "brand":"apple",
        "category":"mobile",
        "image":"https://images.priceoye.pk/apple-iphone-15-pro-pakistan-priceoye-z37xu-500x500.webp",
        "happy":"Reliable computing yet stylish laptop that makes the wallet happy",
        "price":"RS. 549,999",
        "discountpercent":"8",
        "warranty":"1 Year startard warranty",
        "thumbnail":  [
            "https://images.priceoye.pk/apple-iphone-15-pro-pakistan-priceoye-z37xu-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-15-pro-pakistan-priceoye-x8agp-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-15-pro-pakistan-priceoye-w16uh-500x500.webp",
            "https://images.priceoye.pk/apple-iphone-15-pro-pakistan-priceoye-cu3ht-500x500.webp"            
                      ],
        "qty":20
    },
    {
        "id": 46,
        "title": "Redmi 80 cm (32 inches) HD Ready Smart LED Fire TV L32R8-FVIN (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694154515879-819Lw2PE8tL._SL1500_.jpg",
        "price": 138,
        "description": "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz | 178 wide viewing angle\r\nConnectivity: Dual Band Wi-Fi (2.4 GHz/ 5 GHz) | 2 HDMI ports to connect set top box, gaming consoles, DVD or Blu-ray Players | 2 USB ports to connect hard drives and other USB devices | ARC | Bluetooth 5.0 | Ethernet | 3.5mm earphone Jack\r\nSound: 20 Watts Output | Dolby Audio | DTS Virtual: X | DTS-HD\r\nSmart TV Features : Fire TV Built-In | Supported Apps: Prime Video | Netflix | Disney+ Hotstar | YouTube | 12000+ apps from App Store | Voice Remote with Alexa | DTH Set-Top Box Integration to switch between DTH TV Channels and OTT apps from home screen | Display Mirroring - Airplay & Miracast | Quad core ARM Cortex-A35 CPU @ 2.0GHz | 1GB RAM + 8GB Internal Storage\r\nDisplay: Metal bezel-less Screen | Vivid Picture Engine\r\nRecommendation: We recommend using 1.5V Alkaline AAA Batteries in your Alexa Voice Remote for a steady performance.",
        "brand": "redmi",
        "model": "L32R8",
        "color": "black",
        "category": "tv",
        "onSale": true,
        "discount": 7
        },
        {
        "id": 47,
        "title": "Samsung 108 cm (43 inches) Crystal iSmart 4K Ultra HD Smart LED TV UA43CUE60AKLXL (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694154827301-81+JXgPUDLL._SL1500_.jpg",
        "price": 396,
        "description": "Smart TV Features : Supported apps: Netflix, Prime Video, YouTube, etc., Screen mirroring, Universal Guide, Media Home, Tap View, Mobile Camera Support, AI Speaker, Easy Setup, App Casting, Wireless DeX, SmartThings, Smart Hub, IoT Sensor, Web Browser",
        "brand": "samsung",
        "model": "UA43CUE60AKLXL",
        "color": "black",
        "category": "tv",
        "discount": 9
        },
        {
        "id": 48,
        "title": "Mi 125 cm (50 inches) X Series 4K Ultra HD Smart Android LED TV L50M7-A2IN (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694155239807-81UT46-gwRL._SL1500_.jpg",
        "price": 384,
        "description": "Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 hertz | 178° wide viewing angle\r\nConnectivity: Dual Band Wi-Fi (2.4 GHz/ 5 GHz) | 3 HDMI ports to connect latest gaming consoles, set top box, Blu-ray Players | 2 USB ports to connect hard drives and other USB devices | ALLM | eARC | Bluetooth 5.0 | Optical | Ethernet | 3.5mm earphone Jack\r\nSound: 30 Watts Output | Dolby Audio, DTS Virtual: X, DTS-HD\r\nSmart TV Features : Android TV 10 | PatchWall 4 with IMDb integration | Kids Mode with Parental Lock | 300+ Free Live Channels | Universal search | Language Universe (16+ Languages) | India's Top 10 | Miracast | Supported Apps: Prime Video | Netflix | Disney + Hotstar | YouTube | Apple TV | 10000+ apps from Play Store | Quad core A55 CPU processor | Chromecast built-in | Ok Google | Auto Low Latency Mode | 2GB RAM + 8GB Storage\r\nDisplay: 4K HDR | Metal Bezel-less Design | Dolby Vision | HDR10 | HLG | Reality Flow MEMC | Vivid Picture Engine | DCI-P3 94% Colour Gam",
        "brand": "mi",
        "model": "Xiaomi TV X50",
        "color": "black",
        "category": "tv",
        "popular": true,
        "discount": 11
        },
        {
        "id": 49,
        "title": " Acer 126 cm (50 inches) V Series 4K Ultra HD Smart QLED Google TV AR50GR2851VQD (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694155440745-619--Jabh2L._SL1048_.jpg",
        "price": 444,
        "description": "Resolution: QLED, 4K Ultra HD (3840x2160) | Refresh Rate: 60 Hertz | 178 Degree wide viewing angle\r\nConnectivity: Dual band Wifi | 2 way Bluetooth | HDMI ports 2.1 x 3 (HDMI 1 supports eARC) to connect personal computer, laptop, set top box, Blu-ray speakers or a gaming console | USB ports 2.0 x 1, 3.0 x 1 to connect hard drives or other USB device\r\nSound: 30 Watts Output | High Fidelity Speakers with Dolby Atmos | 5 Sound Modes - Stadium, Standard, Movie, Music, Speech\r\nSmart TV Features: Google TV | Content Recommendations | Watchlist | Personal Profile | Kids Profile | Google Assistant | Built-in Chromecast | Voice enabled Smart Remote | Hotkeys for Quick Access - Netflix, Prime Video, YouTube, Disney+Hotstar | Quad Core Processor 2GB RAM | 16GB Storage",
        "brand": "acer",
        "model": "AR50GR2851VQD",
        "color": "black",
        "category": "tv",
        "discount": 5
        },
        {
        "id": 50,
        "title": "LG 139 cm (55 inches) 4K Ultra HD Smart OLED TV 55BXPTA (Dark Steel Silver)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694156089516-71KVQa4N4zL._SL1500_.jpg",
        "price": 1322,
        "description": "Display backlight technology used by the TV \r\nThe number of display pixels in the TV, usually denoted by the number of horizontal pixels multiplies by number of vertical pixels\r\n",
        "brand": "LG",
        "model": "OLED55BXPTA",
        "color": "dark steel silver",
        "category": "tv",
        "discount": 9
        },
        {
        "id": 51,
        "title": " Samsung 138 cm (55 Inches) 4K Ultra HD Smart QLED TV QA55Q80RAKXXL (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694156194279-817zvskL7DL._SL1500_.jpg",
        "price": 2016,
        "description": "Resolution: 4K Ultra HD (3840x2160) | Refresh Rate: 120 hertz\r\nConnectivity: 4 HDMI ports to connect set top box, Blu Ray players, gaming console | 3 USB ports to connect hard drives and other USB devices\r\nSound : 40 Watts Output\r\nSmart TV Features : Smart TV with free apps\r\nDisplay : QLED | LED Panel | Slim and stylish design\r\nWarranty Information: 1 year 1 Year Comprehensive + 1 Year Additional on Panel by Samsung from date of purchase\r\nInstallation: For requesting Samsung sanitized installation/wallmounting/demo of this product once delivered, please directly call Samsung support on [1800407267864/180057267864] and provide product's model name as well as seller's details mentioned on the invoice\r\nWall-Mount: Standard wall-mount (FREE) provided by engineer upon installation request",
        "brand": "samsung",
        "model": "QA55Q80RAKXXL",
        "color": "black",
        "category": "tv",
        "onSale": true,
        "discount": 19
        },
        {
        "id": 52,
        "title": " Samsung 125 cm (50 inches) 4K Ultra HD Smart Neo QLED TV QA50QN90CAKLXL (Carbon Silver)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694156372381-91kw0BYTftL._SL1500_.jpg",
        "price": 1707,
        "description": "Smart TV Features : Built-in Voice Assistant, Far-Field Voice Interaction | Supported apps: Netflix, Prime Video, YouTube, etc., Screen mirroring, Universal Guide, Media Home, Tap View, Mobile Camera Support, Music Wall, AI Speaker, Easy Setup, App Casting, Wireless DeX, SmartThings, Smart Hub, IoT Sensor, Web Browser",
        "brand": "Samsung",
        "model": "QA50QN90CAKLXL",
        "color": "carbon silver",
        "category": "tv",
        "popular": true,
        "discount": 9
        },
        {
        "id": 53,
        "title": " LG 139 cm (55 inches) 4K Ultra HD Smart NanoCell TV 55NANO91TNA (Ceramic Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694156701862-71RgJ4bpoaL._SL1500_.jpg",
        "price": 962,
        "description": "Resolution : 4K Ultra HD (3840 x 2160) | Refresh Rate: 100 hertz | 4K Upscaler\r\nConnectivity: 4 HDMI ports to connect set top box, Blu Ray players, gaming console | 3 USB ports to connect hard drives and other USB devices\r\nSound : 20 Watts Output | 2.0 Ch Speaker| Dolby Atmos | AI Sound | AI Acoustic Tuning\r\nSmart TV Features: webOS Smart TV|α7 Gen3 Processor 4K| AI ThinQ, Built-in Google Assistant & Alexa| Apple Airplay 2 & Homekit| Home Dashboard | Unlimited OTT App Support\r\nDisplay: Real 4K NanoCell Display Technology | Full Array Dimming\r\nWarranty Information: 1 Year LG India Comprehensive Warranty and additional 1 year Warranty is applicable on panel/module from the date of purchase",
        "brand": "LG",
        "model": "NANOCELL",
        "color": "Ceramic Black",
        "category": "tv",
        "popular": true,
        "discount": 9
        },
        {
        "id": 54,
        "title": " TCL 216 cm (85 inches) 4K Ultra HD Smart LED Google TV 85P745 (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694156802350-61IYfIs7m9L._SL1500_.jpg",
        "price": 2405,
        "description": "Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 Hertz\r\nConnectivity: 3 HDMI Ports to connect set top box, Blu Ray players, gaming console | 2 USB Ports | 1 Headphone output\r\nSound: 30 Watts Output | MS12Z wit Dolby Atmos\r\nSmart TV Features: Google TV | 2GB RAM/16 GB Falsh Memory | 64-bit Quad Core Processor | Wifi| Bluetooth | In-Built Apps: Netflix, Prime Video, Disney+Hotstar | Google Assistant | Game Master | 120 Hz Game Acclerator\r\nDisplay: A+ Grade Panel | 178 Degree Wide Viewing Angle | AI Picture Engine | HDR 10 | Wide Color Gamut | Dynamic Color Enhancement | Micro Dimming Technology | MEMC |Ai-CLARITY | Ai-COLOR | Ai-MOTION | Ai-HDR | Ai-CONTRAST | Bezel-Less Full Screen",
        "brand": "TCL",
        "model": "85P745",
        "color": "Black",
        "category": "tv",
        "discount": 15
        },
        {
        "id": 55,
        "title": "TOSHIBA 164 cm (65 inches) 4K Ultra HD Smart QLED Google TV 65M550LP (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694157017146-8115NA1lFdL._SL1500_.jpg",
        "price": 841,
        "description": "‎Google TV | Dolby Vision HDR | Google Assistant | Chromecast, Miracast, DLNA | Auto Low Latency Mode for VRR | Supported Apps : Netflix, Youtube, Prime Video, Hotstar, SonyLiv, Hungama, JioCinema, Zee5, Eros Now",
        "brand": "toshiba",
        "model": "65M550LP",
        "color": "black",
        "category": "tv"
        },
        {
        "id": 56,
        "title": " OnePlus 163 cm (65 inches) Q Series 4K Ultra HD QLED Smart Google TV 65 Q2 Pro (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694157239966-615l0lJ7HEL._SL1500_.jpg",
        "price": 1202,
        "description": "QLED TV | Speak Now™ Hands-free voice control | Remote With Voice Assistant | Google TV | HDR 10+|Dolby Vision | DCI-P3 97% Wide Color Gamut | Supported Applications : Netflix, Disney+Hotstar, Youtube",
        "brand": "onePlus",
        "model": "‎65 Q2 Pro",
        "color": "black",
        "category": "tv",
        "popular": true,
        "onSale": true,
        "discount": 9
        },
        {
        "id": 57,
        "title": " SANSUI 190 cm (75 inches) 4K Ultra HD Smart LED Google TV JSW75GSUHDFF (Pebble Grey)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694157370648-71irUP57QVL._SL1500_.jpg",
        "price": 901,
        "description": "Resolution: 4K Ultra HD (3840x2160) | Refresh Rate: 60 hertz | Wide Viewing Angle\r\nConnectivity: 3 HDMI ports to connect multiple devices | 2 USB ports to connect hard drives and other USB devices|1 AV In|RJ45|Optical out for sound|Wi-Fi|Bluetooth|Ethernet|Antenna\r\nSound: 20 Watts Output | Dolby Atmos | DTS-HD\r\nSmart TV Features: Google TV OS | In-Built WiFi | In-Built Chromecast | 2GB RAM | 32GB ROM | Supported Apps: Netflix, Prime Video, YouTube, Google Play, etc.| Hand free Voice Control, Google Assistant\r\nDisplay: 4K HDR | HDR10 | HLG |Vivid Picture Engine | A+ Grade Panel | Crystal Clear Display | Dynamic Contrast | Bezel-less Design",
        "brand": "SANSUI",
        "model": "JSW75GSUHDFF",
        "color": "Pebble Grey",
        "category": "tv",
        "discount": 7
        },
        {
        "id": 58,
        "title": "Acer 164 cm (65 inches) W Series 4K Ultra HD QLED Smart Android TV AR65AR2851QD (Metallic Grey)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694157446606-91UIOlIz-fL._SL1500_.jpg",
        "price": 962,
        "description": "QLED, Android 11, DCI-P3 98%, Dolby Vision-Atmos, ALLM, Dual Band Wifi, Far Field Mic, Motion Sensor, Blue Light Reduction, MEMC, Dynamic Signal Calibration, Wide Colour Gamut+, 1.07 Billion Colours, HDR10+ with HLG, 4K Upscaling, Digital Noise Reduction, Micro Dimming | Apps : Netflix, Youtube, Prime Video, Hotstar, SonyLiv, Hungama, JioCinema, Zee5, Eros Now, Google Play Store",
        "brand": "Acer",
        "model": "AR65AR2851QD",
        "color": "Metallic Grey",
        "category": "tv",
        "popular": true,
        "discount": 6
        },
        {
        "id": 59,
        "title": "Mi 189.34cm (75 inches) Q1 Series 4K Ultra HD Smart QLED TV L75M6-ESG (Metallic Grey)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694157573546-71fZOKh0i1L._SL1500_.jpg",
        "price": 1563,
        "description": "‎Remote with easy Access like Voice assistant | Ok Google | Quick Wake | Quick Mute | Quick Settings | Dedicated buttons for Netflix and Prime Video",
        "brand": "MI",
        "model": "‎L75M6-ESG",
        "color": "Metallic Grey",
        "category": "tv",
        "discount": 7
        },
        {
        "id": 60,
        "title": " Amaze1 85 Inch WebOS 4KUHD LED TV (AZ85WOUSFL)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694158162881-61g5UoKICfL._SL1500_.jpg",
        "price": 2345,
        "description": "SMART TV, A+ Grade Panel, 3 HDMI, 2 USB, Sound output:Dolby audio ATMOS | Alexa Build-in, ThinIQ, 4KUHD, MEMC, Magic Remote\r\nResolution: HD Ready (3840 x 2160) | Refresh Rate: 60 hertz | Viewing angle: 178 degree, Wireless connectivity, Miracast\r\n1 year warranty, Magic remote, table top stand\r\nWarranty card\r\nTable mount stand\r\n",
        "brand": "Amaze1",
        "model": "AZ85WOUSFL",
        "color": "black",
        "category": "tv",
        "discount": 25
        },
        {
        "id": 61,
        "title": " Onida 124.46 cm (50 Inches) 4K UHD LED Smart TV 50UIB (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694158321609-71pM0BQZLOL._SL1500_.jpg",
        "price": 987,
        "description": "Resolution : 4K Ultra HD (3840x2160) | Refresh Rate: 60 hertz | Viewing Angle: 178 degrees\r\nSmart TV Features: Built-in WiFi | Air Mouse | Mira Cast\r\nConnectivity: 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices | 1 VGA port to connect the laptops\r\nSound : 200 Watts Output\r\nInstallation: For installation/wall mounting/demo of this product once delivered, directly contact Onida at 18001031000 and provide product's model name and seller's details mentioned on your invoice. The service center will allot you a convenient slot for the service\r\nWarranty: 1 year standard manufacturer warranty from Onida",
        "brand": "Onida",
        "model": "50UIB",
        "color": "black",
        "category": "tv",
        "discount": 9
        },
        {
        "id": 62,
        "title": " Hisense 164 cm (65 inches) 4K Ultra HD Smart IPS QLED TV 65U7H (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694158452812-81QyE0wJFYL._SL1500_.jpg",
        "price": 926,
        "description": "Resolution : 4K Ultra HD (3840x2160) | Refresh Rate : 120 Hertz | Full Array Local Dimming | Light Sensing | FreeSync & ALLM VRR Supported\r\nConnectivity: 4 HDMI ports (Ver 2.1) to connect set top box, Blu Ray players, gaming console (HDMI 1 eARC supported) | 1 USB 3.0 and 1 USB 2.0 ports to connect hard drives and other USB devices | Dual-band Wi-Fi | Bluetooth 5.1\r\nSound : 24 Watts Output | Dolby Atmos|Dolby Digital for remarkable sound quality\r\nSmart TV features: Hi View Engine | with Fire TV stick 4k | Auto Low Latency Mode for VRR | Light Sensing | FreeSync Premium | Apps : Netflix, Youtube, Prime Video etc.\r\nDisplay : 120Hz 10 bit Panel | Bezel-less Floating Display Design | ALLM |Dolby Vision, HDR10,HDR10+, HLG | 1 Billion Colours | MEMC",
        "brand": "Hisense",
        "model": "65U7H",
        "color": "black",
        "category": "tv",
        "popular": true,
        "discount": 7
        },
        {
        "id": 63,
        "title": "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV 43UQ8020PSB (Dark Iron Gray)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694158891712-913RqBlzXmL._SL1500_.jpg",
        "price": 420,
        "description": "Resolution: 4K Ultra HD (3840x2160) | Refresh Rate: 60 hertz\r\nConnectivity: Wi-Fi (Built-in) | 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices | eARC | Bluetooth 5.0 | Optical | Ethernet\r\nSound: 20 Watts Output | 2.0 Ch Speaker | AI Sound (Virtual Surround 5.1 up-mix) | Auto Volume Levelling | Bluetooth Surround Ready\r\nSmart TV Features: AI ThinQ & WebOS 22 with User Profiles | Built-in Google Assistant & Alexa | Apple Airplay 2 & Homekit | Game Optimizer & Dashboard | α5 Gen5 AI Processor 4K | Unlimited OTT App Support: Netflix, Prime Video, Disney+ Hotstar, Apple TV, SonyLIV, Discovery+, Zee5 | ALLM & HGiG Mode | HDR 10 Pro & Active HDR | Magic Remote with Hot Keys & Voice Commands",
        "brand": "LG",
        "model": "43UQ8020PSB",
        "color": "Dark Iron Gray",
        "category": "tv",
        "discount": 11,
        "onSale": true
        },
        {
        "id": 64,
        "title": "TCL 189 cm (75 inches) Bezel-Less Full Screen Series Ultra HD 4K Smart LED Google TV 75P635 Pro (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694162974699-714uu8aZdeL._SL1500_.jpg",
        "price": 1325,
        "description": "Google Assistant | 4K Google TV + HDR 10 | AI-IN | T-cast | Apps: Netflix, Youtube, Prime Video & 7000+ Apps | Maximum Content: 10,62,000 Hours | Pure Entertainment",
        "brand": "TCL",
        "model": "75P635 ",
        "color": "black",
        "category": "tv",
        "popular": true,
        "discount": 9
        },
        {
        "id": 65,
        "title": " TCL 163.8 cm (65 inches) X4 65X4US 4K QLED Certified Android Smart TV (Gray)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694163386207-71twiKmSQJL._SL1500_.jpg",
        "price": 1297,
        "description": "The ultra HD (3840 x 2160) resolution is 4 times greater than full HD. You will be captivated by the perfect precisions of the images on our ultra HD TVs that displays an image with over 8 million pixels. The upscale technology could upgrade 2K image to 4K quality from USB, HDMI and online live content.",
        "brand": "TCL",
        "model": "X4 65X4US",
        "color": "grey",
        "category": "tv",
        "popular": true,
        "discount": 9,
        "onSale": true
        },
        {
        "id": 66,
        "title": " Daktron 85 Inch 4K Ultra HD Smart Android LED TV",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694163546968-41LoWsH3o-L (1).jpg",
        "price": 768,
        "description": "Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 120 hertz\r\nConnectivity: 4 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices\r\nDisplay : A+ Grade Panel | UHD | HDR | Slim Design\r\nWarranty Information: 1 year warranty",
        "brand": "Generic",
        "model": "Daktron 2022",
        "color": "black",
        "category": "tv",
        "discount": 7
        },
        {
        "id": 67,
        "title": " MI 80 cm (32 inches) 5A Series HD Ready Smart Android LED TV L32M7-5AIN (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165099348-81xT3no1+6L._SL1500_.jpg",
        "price": 150,
        "description": "Resolution : HD Ready (1366 x 768) Resolution | Refresh Rate : 60 Hertz | 178 Degree wide viewing angle\r\nConnectivity: Dual Band Wi-Fi | 2 HDMI ports to connect latest gaming consoles, set top box, Blu-ray Players | 2 USB ports to connect hard drives and other USB devices | ALLM | ARC | Bluetooth 5.0 | Ethernet\r\nSound: 20 Watts Output | Dolby Audio, DTS Virtual: X, DTS-HD\r\nSmart TV Features : Android TV 11 | PatchWall | IMDb Integration | Universal Search | 300+ Free Live Channels | Kids Mode with Parental lock | Smart Recommendations | Language Universe – 15+ Languages | User Centre | Okay Google | Chromecast suporting Apps : Netflix, Prime Video, Disney+ Hotstar | 5000+ apps from Play Store |Quad core Cortex A35 | Chromecast built-in | Ok Google | Auto Low Latency Mode | 1GB RAM + 8GB Storage",
        "brand": "MI",
        "model": "‎L32M7-5AIN",
        "color": "black",
        "category": "tv",
        "discount": 9
        },
        {
        "id": 68,
        "title": " LG 80 cm (32 inches) HD Ready Smart LED TV 32LM563BPTC (Dark Iron Gray)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165166892-71D6DfO-0nL._SL1500_.jpg",
        "price": 162,
        "description": "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz\r\nConnectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices\r\nSound output: 10 Watts Output I 2 Speakers | DTS Virtual:X | Sound Type : Down FiringSmart\r\nTV Features: Web OS Smart TV | Wi-Fi | Home Dashboard | Screen Mirroring | Mini TV Browser | Multi-Tasking | Office 365, Set WXHXD (with Stand ) mm - 739 x 472 x 168Display: Active HDR | Display Type: Flat | BackLight Module: Slim LED\r\nWarranty Information: 1 Year LG India Comprehensive Warranty and additional 1 year Warranty is applicable on panel/module from the date of purchase (Offer Valid till 31st August 2022)\r\nInstallation: For requesting installation/wall mounting/demo of this product once delivered, please directly call LG support on 1800 180 9999/1800 315 9999 and provide product's model name as well as seller's details mentioned on the invoiceEasy",
        "brand": "LG",
        "model": "32LM563BPTC",
        "color": "grey",
        "category": "tv",
        "discount": 3
        },
        {
        "id": 69,
        "title": "Acer 80 cm (32 inches) Advanced I Series HD Ready Smart LED Google TV AR32GR2841HDFL (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165291672-511DmhAgHAL._SL1073_.jpg",
        "price": 156,
        "description": "Resolution: HD Ready (1366x768) | Refresh Rate: 60 Hertz | 178 Degree wide viewing angle\r\nConnectivity: Dual band Wifi | 2 way Bluetooth | HDMI ports 2.0 x 2 (HDMI 1 supports ARC) to connect personal computer, laptop, set top box, Blu-ray speakers or a gaming console | USB ports 2.0 x 2 to connect hard drives or other USB device\r\nSound: 30 Watts Output | High Fidelity Speakers with Dolby Audio | 5 Sound Modes - Stadium, Standard, Movie, Music, Speech\r\nSmart TV Features: Google TV | Content Recommendations | Watchlist | Personal Profile | Google Assistant | Built-in Chromecast | Voice enabled Smart Remote | Hotkeys for Quick Access - Netflix, Prime Video, YouTube, Disney+Hotstar | Quad Core Processor 1.5GB RAM | 16GB Storage\r\nDisplay : 16.7 Million Colours | Intelligent Frame Stabilization Engine | HDR10 | Super Brightness | Micro Dimming | Blue Light Reduction",
        "brand": "acer",
        "model": "AR32GR2841HDFL",
        "color": "black",
        "category": "tv",
        "discount": 5
        },
        {
        "id": 70,
        "title": " TOSHIBA 80 cm (32 inches) V Series HD Ready Smart Android LED TV 32V35MP (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165393188-917cT1r-aUL._SL1500_.jpg",
        "price": 150,
        "description": "Official Android TV 11(R) | Built-in Assistant | RAM: 1GB | ROM 8 GB | Quad Core Processor | Supported Apps : Netflix, Prime Video, Disney+ Hotstar etc on Official Play Store",
        "brand": "toshiba",
        "model": "32V35MP",
        "color": "black",
        "category": "tv",
        "discount": 9
        },
        {
        "id": 71,
        "title": " LG 80 cm (32 inches) HD Ready Smart LED TV 32LQ576BPSA (Ceramic Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165528390-71IBre-QupL._SL1500_.jpg",
        "price": 192,
        "description": "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz | Resolution Upscaler | 178 Degree wide viewing angle\r\nConnectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices | 2-Way Bluetooth\r\nSound: 10 Watts Output | Dolby Digital Plus Sound Configuration | AI Sound | Virtual Surround 5.1 | Bluetooth Surround Ready | AI Acoustic Tuning\r\nSmart TV Features: α5 Gen 5 AI Processor | Web OS Operating System | Wi-Fi | Magic Remote | Full Web Browser | Screen Share | Game Optimizer | Built-in Alexa | Google Assistant | AI Functions | Works with Apple AirPlay & Homekit | HDR 10 Pro | 8 GB Storage | Supported Apps: Prime Video, Netflix, Disney+ Hotstar, Sony Liv, Zee5, Apple TV and more\r\nDisplay: LED Panel | HD Ready Digital Video Format | Slim & Stylish Design\r\nWarranty Information: 1 Year LG India Comprehensive Warranty and additional 1 year Warranty is applicable on panel/module from the date of purchase\r\nInstallation : For requesting installation/wall mounting/demo of this product once delivered, please directly call LG support (Please visit LG Website for Toll Free Numebrs) and provide product's model name as well as seller's details mentioned on the invoice",
        "brand": "LG",
        "model": "32LQ576BPSA",
        "color": "ceremic black",
        "category": "tv",
        "discount": 3
        },
        {
        "id": 72,
        "title": " Kodak 80 cm (32 inches) HD Ready Certified Android LED TV 32HDX7XPRO (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165648075-81pOKCk2z1L._SL1500_.jpg",
        "price": 132,
        "description": "‎Smart remote with Dedicated Hotkeys for quick and easy access | Google Voice Assistant",
        "brand": "Kodak",
        "model": "32HDX7XPRO",
        "color": "black",
        "category": "tv",
        "discount": 5
        },
        {
        "id": 73,
        "title": " SANSUI 80 cm (32 inches) HD Ready Smart A+ LED Google TV JSWY32GSHD (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165731813-717jM0kdi8L._SL1500_.jpg",
        "price": 150,
        "description": "Smart TV Features: Google TV | Google Assistant | Built-in Chromecast | Voice Search Smart Remote | Supported Apps: Netflix, Youtube, Prime Video, Disney+ Hotstar, Google Play",
        "brand": "SANSUI",
        "model": "JSWY32GSHD",
        "color": "black",
        "category": "tv",
        "discount": 5,
        "onSale": true
        },
        {
        "id": 74,
        "title": " HYUNDAI 80 cm (32 inches) HD Ready Smart LED TV SMTHY32WSR6YI5 (Black)",
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694165821925-71hoDN+6NfL._SL1500_.jpg",
        "price": 132,
        "description": "Resolution : HD Ready (1366x768) | Refresh Rate : 60 Hertz | 178 Degree wide viewing angle\r\nConnectivity: 3 HDMI ports to connect set top box, Blu-ray speakers or a gaming console | 2 USB ports to connect hard drives or other USB devices | Ethernet Port For Wired Network\r\nSound: 20 Watts Output | Box Speaker For Superior Sound | 6 Sound Modes | Dolby Ultra Surround\r\nSmart TV Features: Webos | Simplink (Hdmi Cec",
        "brand": "Hyundai",
        "model": "SMTHY32WSR6YI5",
        "color": "black",
        "category": "tv",
        "discount": 3
        }
]